apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-test1
  project: giri-may
spec:
  base:
    name: default
    version: 2.7.0
  componentsCriticality:
  - name: xwing-fail
  - name: redis-catalog
  customAddons:
  - name: rabbitmq
    version: rabbitmq-v1
  - name: redis-catalog
    version: redis-v1
  - name: xwing-fail
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v9
