apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-v1
  project: giri-may
spec:
  base:
    name: minimal
    version: 2.7.0
  customAddons:
  - name: xwing-fail
    version: v1
  defaultAddons:
    enableIngress: true
  driftWebhook:
    enabled: true
  type: custom
  version: version2
