apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: default-cb
  project: giri-may
spec:
  base:
    name: minimal
    version: 2.7.0
  componentsCriticality:
  - name: xwing-fail
  - name: opa-policy
  customAddons:
  - name: xwing-fail
    version: v1
  defaultAddons:
    enableIngress: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  opaPolicy:
    opaPolicy:
    - name: requiredlabels
      version: v1
    profile:
      name: new
      version: v1
  type: custom
  version: opa-label
