apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: np-fail
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.7.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  networkPolicy:
    policies:
    - name: ccnp2
      version: v2
    - name: ccnp3
      version: v1
    - name: new
      version: v1
    profile:
      name: default
      version: latest
  type: custom
  version: v4
